Matriz
kevv87/Dots pull request #6
Opened 2018-09-12 22:33 UTC by fabian152195

Matriz del server y funcionalidad de conectar puntos.

2018-09-13 02:00 UTC, kevv87 commented
Tiene dos errores de convención según CodeFactor, @fabian152195

2018-09-13 02:03 UTC, fabian152195 commented
En realidad son sugerencias, pero no las voy a corregir :P. Son ifs, y
quiere q los cambie por returns. Si lo hago, se cae la vara.

El mié., 12 de sep. de 2018 8:00 p.m., kevv87 <notifications@github.com>
escribió:

> Tiene dos errores de convención según CodeFactor, @fabian152195
> <https://github.com/fabian152195>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kevv87/Dots/pull/6#issuecomment-420857465>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AlLnYyqrFS_5rTmDFQCXJZaXnUhIIbERks5uabwqgaJpZM4WmRjA>
> .
>

2018-09-13 16:10 UTC, kevv87 commented on Interfaz/MarcoJuego.java
> +        lamina.addLine(1,2, Color.yellow);
Casos de prueba, borrar

2018-09-13 16:10 UTC, kevv87 commented on Interfaz/LaminaJuego.java
>                  lineas.agregarAlInicio(new Linea(x1,y1,x2,y2,color));
Creo que al final no funciona este algoritmo

2018-09-13 16:42 UTC, kevv87 requested changes

2018-09-13 16:42 UTC, kevv87 commented on Eventos/EventosMouse.java
> +        System.out.println("x: "+ x + ", y: "+y);
Quitar prints a consola

2018-09-13 16:42 UTC, kevv87 commented on Matriz/Matriz.java
> +            ListaPuntos tmpH = headMatriz;
Nombre mas especifico

2018-09-13 16:42 UTC, kevv87 commented on Matriz/Matriz.java
> +            ListaPuntos tmpH = headMatriz;
Quizas aux?

2018-09-13 16:42 UTC, kevv87 commented on Matriz/Matriz.java
> +    public boolean inicializaMatriz(int c_Filas, int c_Columnas){
Return void

2018-09-13 16:42 UTC, kevv87 commented on Matriz/Matriz.java
> +            punto2.getListaRelaciones().listar();
Quite los outputs en consola

2018-09-14 19:06 UTC, fabian152195 commented on Matriz/Matriz.java
> +    public boolean inicializaMatriz(int c_Filas, int c_Columnas){
por el momento, dejémoslo así, por aquello que querramos hacer la matriz dinámica.. 👯‍♂️

2018-09-16 00:10 UTC, kevv87 approved these changes

2018-09-16 00:10 UTC, merged